[package]
name = "oxidd-core"
version = "0.1.0"
edition = "2021"
description = "Core traits and types of the OxiDD decision diagram framework"
license = "MIT OR Apache-2.0"

[dependencies]
nanorand = { version = "0.7.0", default-features = false, features = ["wyrand"] }
